image: gcc

before_script:
  - apt-get update -y
  - apt-get install cmake googletest

stages:
  - build
  - test

build:
  stage: build
  script:
    - make build

test:
  stage: test
  script:
    - make test
